name: Test Project

# on: push
# on: [push, disaptch_workflow]

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "!src/docs/**"
    pull_request:
        branches: [main]
        types: [opened, closed]
        
jobs:
    typecheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
              with:
                ref: main
                # ref: dev
            - name: Install Dependencies
              run: npm ci
            
            - name: Run Typecheck
              run: npm run typecheck
    lint:
        needs: typecheck
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
              with:
                ref: main
                # ref: dev
            - name: Install Dependencies
              run: npm ci
            
            - name: Run Lint Check
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
              with:
                ref: main
                # ref: dev
            - name: Install Dependencies
              run: npm ci
            
            - name: Run tests
              run: npm test